name: Compile MQL5 EAs

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MetaEditor & Compile
        uses: fx31337/mql-compile-action@master
        with:
          include: '.'
          init-platform: true

      - name: Upload Compiled EX5 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-ex5-bots
          path: |
            *.ex5
